name: pull-request
on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - changeset-release/*
      - vis-bot/update-snapshot/*
jobs:
  verify:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18
          - 20
          - 22
    runs-on: ${{ matrix.os }}
    env:
      PLAYWRIGHT_PATH: "~/.cache/ms-playwright"
    steps:
      - name: Get AppData Directory
        if: matrix.os == 'windows-latest'
        run: echo ("PLAYWRIGHT_PATH=" + $env:LOCALAPPDATA + "\ms-playwright") >> $env:GITHUB_ENV

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        id: cache-playwright
        with:
          path: ${{ env.PLAYWRIGHT_PATH }}
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install playwright browsers
        run: pnpx playwright install --with-deps chromium firefox
        if: steps.cache-playwright.outputs.cache-hit != 'true'

      - name: Install Dependencies
        run: pnpm install

      - name: Verify
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm verify

      - name: Archive snapshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: snapshots
          path: |
            '**/__vis__/__diff_output__'
            '**/__vis__/__results__'
